<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>ijs</string>
    </array>

    <key>name</key>
    <string>J</string>

    <key>patterns</key>
    <array>
        <dict>
            <key>name</key>
            <string>string.j</string>

            <key>match</key>
            <string>('[^']*')</string>
        </dict>


        <dict>
            <key>name</key>
            <string>comment.j</string>

            <key>match</key>
            <string>(?:^|[ )])(NB\..*$)</string>
        </dict>
        <dict>
            <key>name</key>
            <string>constant.numeric.j</string>

            <key>match</key>
            <string>(?&lt;![_a-zA-Z])([_0-9][_0-9a-zA-Z]*\.?[0-9a-zA-Z]*)(?![\.\:])</string>
        </dict>

        <dict>
            <key>name</key>
            <string>copula.global.j</string>

            <key>match</key>
            <string>=\:</string>
        </dict>

        <dict>
            <key>name</key>
            <string>copula.local.j</string>

            <key>match</key>
            <string>=\.</string>
        </dict>

        <dict>
            <key>name</key>
            <string>keyword.j</string>

            <key>match</key>
            <string>(?:^|(?&lt;=[) ]))((?:while\.)|(?:whilst\.)|(?:if\.)|(?:elseif\.)|(?:else\.)|(?:do\.)|(?:end\.))</string>
        </dict>

        <dict>
            <key>name</key>
            <string>noun.j</string>

            <key>match</key>
            <string>(?:(_\.|a\.|a:)(?![\.\:]))</string>
        </dict>

        <dict>
            <key>name</key>
            <string>conjunction.j</string>

            <key>match</key>
            <string>((?:[dDHT]\.)|(?:[DLS]:)|(&amp;\.:)|([\;\!\@&amp;]\.)|([\^\!\`\@&amp;]:)|([\"\`\@&amp;])|(\s[\.\:][\.\:])|(\s[\.\:]))(?![\.\:])</string>
        </dict>

        <dict>
            <key>name</key>
            <string>adverb.j</string>

            <key>match</key>
            <string>(([\/\\]\.)|(?:[bfMt]\.)|(?:t:)|([\~\/\\\}]))(?![\.\:])</string>
        </dict>

        <dict>
            <key>name</key>
            <string>verb.j</string>

            <key>match</key>
            <string>((?:_?[0-9]\:)|(?:p\.\.)|(?:[AcCeEiIjLopr]\.)|(?:[ipqsux]:)|({::)|([&lt;&gt;\+\*\-\%\^\$\~\|\,\#\{\}&quot;\?]\.)|([&lt;&gt;\_\+\*\-\%\$\~\|\,\;\#\/\\\[\{\}&quot;]:)|([&lt;&gt;\=\+\*\-\%\^\$\|\,\;\#\!\[\]\{\?]))(?![\.\:])</string>
        </dict>
    </array>

    <key>scopeName</key>
    <string>source.j</string>
</dict>
</plist>